AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/MixinGrouping:
  Enabled: false
Style/BlockComments:
  Enabled: false
